export { ClassificationConfirmationDialog } from './ConfirmationDialog'
export { EditorArea } from './EditorArea'
export type { EditorAreaProps, EditorHandle, DocumentStats, EditorCommand, FileImportMode } from './editor-area.types'
export { EditorFooter } from './EditorFooter'
export { EditorHeader } from './EditorHeader'
export type { HeaderActionId } from './EditorHeader'
export { EditorSidebar } from './EditorSidebar'
export type { SidebarSection } from './EditorSidebar'
export { EditorToolbar } from './EditorToolbar'
export type { ToolbarActionId } from './EditorToolbar'
export { ScreenplayEditor, mountScreenplayEditor } from './ScreenplayEditor'
