export const PPI = 96
export const PAGE_HEIGHT_PX = 1123
export const PAGE_WIDTH_PX = 794
export const HEADER_HEIGHT_PX = 96
export const FOOTER_HEIGHT_PX = 96
export const PAGE_MARGIN_TOP_PX = 77
export const PAGE_MARGIN_BOTTOM_PX = 77
export const PAGE_MARGIN_LEFT_PX = 96
export const PAGE_MARGIN_RIGHT_PX = 120
export const CONTENT_HEIGHT_PX = PAGE_HEIGHT_PX - PAGE_MARGIN_TOP_PX - PAGE_MARGIN_BOTTOM_PX
